project_django/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

# TODO: Implement Routings Here

todolist/urls.py
from django.urls import include, path
from todolist.views import show_todolist
from todolist.views import register
from todolist.views import login_user
from todolist.views import logout_user
from todolist.views import create_task
from todolist.views import finish_task
from todolist.views import delete_task
from todolist.views import show_json
from todolist.views import show_todolist_ajax
from todolist.views import create_task_ajax
from todolist.views import delete_task_ajax
from todolist.views import toggle_finish

app_name = 'todolist'

urlpatterns = [
    path('', show_todolist_ajax, name='show_todolist'),
    path('create-task/', create_task, name='create-task'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('finish-task/<int:pk>', finish_task, name='finish-task'),
    path('delete-task/<int:pk>', delete_task, name='delete-task'),
    path('json/', show_json, name='show_json'),
    path('old', show_todolist, name='show_todolist_old'),
    path('create-task-ajax/', create_task_ajax, name='create-task-ajax'),
    path('delete-task-ajax/<int:pk>', delete_task_ajax, name='delete-task-ajax'),
    path('toggle-finsih/<int:pk>', toggle_finish, name='toggle'),

]

todolist/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.TextField()
    description = models.TextField()
    is_finished = models.TextField()

todolist/forms.py
from django import forms
from .models import Task

class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['title', 'description']

    def __str__(self):
        return ""

todolist/views.py
from django.shortcuts import render
from .forms import TaskForm
from todolist.models import Task
from django.http import HttpResponse, HttpResponseNotFound
from django.core import serializers
from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

# Create your views here.
@login_required(login_url='/todolist/login/')

# Fungsi yang menampilkan list to-do
def show_todolist(request):
    data_todolist = Task.objects.filter(user=request.user)
    context = {
        'list': data_todolist,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

# Fungsi yang membuat task baru
def create_task(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.datetime.now()
        user = request.user
        is_finished = "❎"
        Task.objects.create(title=title, description=description, date=date, user=user, is_finished=is_finished)
        return redirect('todolist:show_todolist_old')
    return render(request,"create-task.html")

# Fungsi untuk handle register
def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)

# Fungsi untuk handle login
def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    
    return render(request, 'login.html', context)

# Fungsi untuk handle logout
def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    response.delete_cookie('last_login')
    return response

# Fungsi yang mengganti status task
def finish_task(request, pk):
    task = Task.objects.get(id=pk)
    task.is_finished = "✅"
    task.save()
    return redirect('todolist:show_todolist')

# Fungsi yang menghapus task
def delete_task(request, pk):
    task = Task.objects.get(id=pk)
    Task.delete(task)
    return redirect('todolist:show_todolist_old')

def show_json(request):
    task = Task.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize('json', task))

def show_todolist_ajax(request):	
    data_todolist = Task.objects.filter(user=request.user)
    context = {
        'task': data_todolist,
        'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist-ajax.html", context)

def create_task_ajax(request):
    if request.method == 'POST':
        title = request.POST.get('title')
        description = request.POST.get('description')
        date = datetime.datetime.now()
        user = request.user
        is_finished = "❎"
        new_task = Task(title=title, description=description, date=date, user=user, is_finished=is_finished)
        new_task.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()

def delete_task_ajax(request, pk):
    data = Task.objects.get(id=pk)
    data.delete()
    response = HttpResponseRedirect(reverse("todolist:show_todolist"))
    return response

def toggle_finish(request, pk):
    data = Task.objects.get(id=pk)
    if data.is_finished == "✅":
        data.is_finished = "❎"
    else:
        data.is_finished = "✅"
    data.save()
    response = HttpResponseRedirect(reverse("todolist:show_todolist"))
    return response

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block content %}
<div class="create-task">
    <style>
        .gradient-custom {
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, rgb(211, 170, 255), rgb(166, 199, 255))
        }
        body {
            overflow: hidden;
        }
    </style>

    <form method="POST" action="">
        {% csrf_token %}
        <!-- <table>
            <tr>
                <td>To-do: </td>
                <td><input type="text" name="title" class="form-control"></td>
            </tr>
    
            <tr>
                <td>Description: </td>
                <td><input type="text" name="description" class="form-control"></td>
            </tr>
    
            <tr>
                <td></td>
                <td><input class="submit" type="submit" value="Create"></td>
            </tr>
        </table> -->
    
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100 ">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                  <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center rounded">
          
                      <div class="mb-md-5 mt-md-4 pb-5 px-2 py-2 bg-light text-dark rounded">
                        <div class="form-outline form-dark mb-4">
                            <input type="text" name="title" class="form-control"/>
                          <label class="form-label" for="typeTitle">Title</label>
                        </div>
    
                        <div class="mb-md-5 mt-md-4 pb-5 px-2 bg-light text-dark">
                            <div class="form-outline form-dark mb-4">
                                <input type="text" name="description" class="form-control"/>
                            <label class="form-label" for="typeDesc">Description</label>
                        </div>
    
                        <td><input class="btn btn-outline-dark btn-lg px-5" type="submit" value="Create"></td>
    
    
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </section>
    </form>

</div>
{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}

<div class = "login">

    <!-- <h1>Login</h1>

    <form method="POST" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td><input type="text" name="username" placeholder="Username" class="form-control"></td>
            </tr>
                    
            <tr>
                <td>Password: </td>
                <td><input type="password" name="password" placeholder="Password" class="form-control"></td>
            </tr>

            <tr>
                <td></td>
                <td><input class="btn login_btn" type="submit" value="Login"></td>
            </tr>
        </table>
    </form>

    {% if messages %}
        <ul>
            {% for message in messages %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a> -->
    <style>
        .gradient-custom {
            /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
            background: linear-gradient(to right, rgb(211, 170, 255), rgb(166, 199, 255))
        }
    </style>

    <form method="POST" action="">
        {% csrf_token %}
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                  <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center rounded">
          
                      <div class="mb-md-5 mt-md-4 pb-5">
          
                        <h2 class="fw-bold mb-2 text-uppercase">Login</h2>
                        <p class="text-white-50 mb-5">Please enter your login and password!</p>
          
                        <div class="form-outline form-white mb-4">
                            <input type="text" name="username" placeholder="Username" class="form-control"/>
                          <label class="form-label" for="typeUsername">Username</label>
                        </div>
          
                        <div class="form-outline form-white mb-4">
                            <input type="password" name="password" placeholder="Password" class="form-control"/>
                          <label class="form-label" for="typePassword">Password</label>
                        </div>
                
                        <!-- <button class="btn btn-outline-light btn-lg px-5" type="submit" val ></button> -->
                        <td><input class="btn btn-outline-light btn-lg px-5" type="submit" value="Login"></td>
                      </div>
          
                        {% if messages %}
                            <ul>
                                {% for message in messages %}
                                    <div class="alert alert-warning alert-dismissible fade show" role="alert">
                                        {{message}}
                                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                    </div>
                                {% endfor %}
                            </ul>
                        {% endif %}

                      <div>
                        <p class="mb-0">Don't have an account? <a href="{% url 'todolist:register' %}" class="text-white-50 fw-bold">Sign Up</a>
                        </p>
                      </div>

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
    
    </div>
    </form>
    

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  
<style>
    .gradient-custom {
        /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
        background: linear-gradient(to right, rgb(211, 170, 255), rgb(166, 199, 255))
    }
</style>

<div class = "register">


    <form method="POST" action="">
        {% csrf_token %}
        <section class="vh-100 gradient-custom">
            <div class="container py-5 h-100">
              <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-12 col-md-8 col-lg-6 col-xl-5">
                  <div class="card bg-dark text-white" style="border-radius: 1rem;">
                    <div class="card-body p-5 text-center">
          
                      <div class="mb-md-5 mt-md-4 pb-5 bg-light text-dark rounded">
          
                        <form method="POST" >  
                            {% csrf_token %}  
                            <table>  
                                {{ form.as_table }}  
                                <tr>  
                                    <td></td>
                                    <td><input type="submit" name="submit" value="Daftar"/></td>  
                                </tr>  
                            </table>  
                        </form>
                
                        {% if messages %}  
                            <ul>   
                                {% for message in messages %}  
                                    <li>{{ message }}</li>  
                                    {% endfor %}  
                            </ul>   
                        {% endif %}

                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
    
    </div>
    </form>

</div>  

{% endblock content %}

todolist/templates/todolist-ajax.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<script>window.CSRF_TOKEN = "{{ csrf_token }}"</script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
{% endblock meta %}

{% block content %}
<!-- <form id="form" onsubmit="return false;">
    {% csrf_token %}
    <label>Judul</label>
    <input type="text" name="title"></input>
    <label>Deskripsi</label>
    <input type="text" name="deskripsi"></input>
    <button id="button" type="submit"  value="Submit"></button>
  </form> -->




  
<style>
  .gradient-custom {
    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(to right, rgb(211, 170, 255), rgb(166, 199, 255))
  }

  .navbar-custom {
    background: linear-gradient(to left, rgb(255, 229, 246), rgb(189, 213, 255))
  }

  .card{
    border-radius: 4px;
    background: #fff;
    box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
    transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
    padding: 14px 80px 18px 36px;
    cursor: pointer;
  }

  .card:hover{
    transform: scale(1.05);
    box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
  }

  body {
          overflow-x: hidden;
      }
</style>



<div class="navbar fixed-top navbar-custom color-custom shadow-lg p-3 mb-5 ">

  <h1 class="px-2" style="text-align: center;">Assignment 4 PBP/PBD<br></h1><br>


  <h2 class="px-2" style="text-align: center;">
    <button class="btn btn-outline-light btn-lg px-5" data-bs-toggle="modal" data-bs-target="#exampleModal" >Create Task</button>
  
    <button class="btn btn-outline-light btn-lg px-5">
      <a href="{% url 'todolist:logout' %}"> Logout</a>
    </button>
  </h2>

</div>

<div class="gradient-custom">
  <br><br><br>
  <!-- <table id="table"></table> -->


  
  <div class="container">
    <div class="row row-cols-4 g-5 py-5 px-5 row d-flex justify-content-center" id="cardcontainer"></div>
 
  </div>

  <!-- {% if task %}
  <div class="container">

    <div class="row row-cols-4 g-5 py-5 px-5 row d-flex justify-content-center">
      {% comment %} Add the data below this line {% endcomment %}
      {% for item in task %}
      
        <div class="col-12 col-md-6 col-lg-4">
          <div class="card .bg-light .bg-gradient rounded">
            <div class="card-body">
              <h5 class="card-title">{{item.title}}</h5>
              <p class="card-text">{{item.description}}</p>
              <h5 class="card-date">{{item.date}}</h5>
              <a href="{% url 'todolist:delete-task' item.id %}">Delete</a>
            </div>
          </div>
        </div>
      {% endfor %}

  </div>

  {% else %}
  <p>No Task Available</p>
  {% endif %} -->
  </div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Create Task</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <form action="" id="form">
            {% csrf_token %}
                <div class="mb-md-5 mt-md-4 pb-5 px-2 py-2 bg-light text-dark rounded">
                    <div class="form-outline form-dark mb-4">
                        <input type="text" name="title" class="form-control"/>
                      <label class="form-label" for="typeTitle">Title</label>
                    </div>

                    <div class="mb-md-5 mt-md-4 pb-5 px-2 bg-light text-dark">
                        <div class="form-outline form-dark mb-4">
                            <input type="text" name="description" class="form-control"/>
                        <label class="form-label" for="typeDesc">Description</label>
                    </div>
            </form>
        </div>
        <div class="modal-footer">
            <td><button class="btn btn-outline-dark btn-lg px-5" id="button" data-bs-dismiss="modal" onsubmit="return false;">Create</button></td>
        </div>
      </div>
    </div>
  </div>

  <script>
    $(document).ready(function()  {
      refreshTodolist();
    });
    
    async function getTodolist() {
      return fetch("{% url 'todolist:show_json' %}").then((res) => res.json())
    }
  
    async function refreshTodolist() {
          document.getElementById("cardcontainer").innerHTML = ""
          const todolist = await getTodolist()
          let htmlString = ``
          todolist.forEach((item) => {
            htmlString += `<div class="col-12 col-md-6 col-lg-4">
          <div class="card .bg-light .bg-gradient rounded">
            <div class="card-body">
                <h5 class="card-title">${item.fields.title}</h5>
                <h6 class="card-subtitle mb-2 text-muted">${item.fields.date}</h6>
                <p class="card-text">${item.fields.description}</p>
                <p class="card-text"></p> 
                {% if task.is_finished %}
                <p class="card-text">✅</p>
                {% else %}
                <p class="card-text">❎</p>
                {% endif %}

                <button class="bg-green-500 rounded-2xl p-2 text-white font-bold delete" onclick="ToggleStatus(${item.pk})">Finish</button>
                <button class="bg-green-500 rounded-2xl p-2 text-white font-bold delete" onclick="deleteTask(${item.pk})">Delete</button>
            </div>
          </div>
        </div>` 
          })
          
          document.getElementById("cardcontainer").innerHTML = htmlString
    }
  
    function addTodolist() {
      fetch("{% url 'todolist:create-task-ajax' %}", {
            method: "POST",
            body: new FormData(document.querySelector('#form'))
        }).then(refreshTodolist)
      return false
    }

    function deleteTask(id) {
        $.ajax({
            type: "GET",
            url: "/todolist/delete-task-ajax/" + id,
            data: {csrfmiddlewaretoken: '{{ csrf_token }}'}
        }).done((data) => {
            refreshTodolist();
        })
    }

    function toggleStatus(id) {
        $.ajax({
            type: "GET",
            url: "/todolist/toggle-finish/" + id,
            data: {csrfmiddlewaretoken: '{{ csrf_token }}', pk: id}
        }).done((data) => {
            refreshTodolist();
        })
    }

    document.getElementById("button").onclick = addTodolist
    
    refreshTodolist()
  </script>

  <h5></h5>


  <h5 style = "font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 32px; color: blue; text-align: center;">{{status}}</h5>


 {% endblock content %}
</div>

todolist/templates/todolist.html
{% extends 'base.html' %}

 {% block content %}
  
  <style>
    .gradient-custom {
      /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
      background: linear-gradient(to right, rgb(211, 170, 255), rgb(166, 199, 255))
    }

    .navbar-custom {
      background: linear-gradient(to left, rgb(255, 229, 246), rgb(189, 213, 255))
    }

    .card{
      border-radius: 4px;
      background: #fff;
      box-shadow: 0 6px 10px rgba(0,0,0,.08), 0 0 6px rgba(0,0,0,.05);
      transition: .3s transform cubic-bezier(.155,1.105,.295,1.12),.3s box-shadow,.3s -webkit-transform cubic-bezier(.155,1.105,.295,1.12);
      padding: 14px 80px 18px 36px;
      cursor: pointer;
    }

    .card:hover{
      transform: scale(1.05);
      box-shadow: 0 10px 20px rgba(0,0,0,.12), 0 4px 8px rgba(0,0,0,.06);
    }

    body {
            overflow-x: hidden;
        }
  </style>



  <div class="navbar fixed-top navbar-custom color-custom shadow-lg p-3 mb-5 ">

    <h1 class="px-2" style="text-align: center;">Assignment 4 PBP/PBD<br></h1><br>


    <h2 class="px-2" style="text-align: center;">
      <button class="btn btn-outline-light btn-lg px-5">
        <a href="{% url 'todolist:create-task' %}"> Create Task</a>
      </button>
    
      <button class="btn btn-outline-light btn-lg px-5">
        <a href="{% url 'todolist:logout' %}"> Logout</a>
      </button>
    </h2>

  </div>
  

  <div class="gradient-custom">
    <br><br><br>
    {% if list %}
    <div class="container">

      <div class="row row-cols-4 g-5 py-5 px-5 row d-flex justify-content-center">
        {% comment %} Add the data below this line {% endcomment %}
        {% for item in list %}
        
          <div class="col-12 col-md-6 col-lg-4">
            <div class="card .bg-light .bg-gradient rounded">
              <div class="card-body">
                <h5 class="card-title">{{item.title}}</h5>
                <p class="card-text">{{item.description}}</p>
                <h5 class="card-date">{{item.date}}</h5>
                <a href="{% url 'todolist:delete-task' item.id %}">Delete</a>
              </div>
            </div>
          </div>
        {% endfor %}

    </div>

    {% else %}
    <p>No Task Available</p>
    {% endif %}
    </div>
    <h5></h5>
  
  
    <h5 style = "font-family: Verdana, Geneva, Tahoma, sans-serif; font-size: 32px; color: blue; text-align: center;">{{status}}</h5>
  
  
   {% endblock content %}
  </div>